### PR TITLE
Models with coulomb friction explicitly enabled

### PR DESCRIPTION
**Pull request by diegoferigo**
@nunoguedelha 
I'm opening this PR here just for convenience, I'm temporarily using your fork waiting your branch will get merged upstream. Can you please merge this here for the time being?

### CODE REVIEW

**Review by nunoguedelha — APPROVED** [review]
@diegoferigo , not that it is really important at this point, but is it normal that the friction is 0.02 and not 0.00 for a few joints like the elbow?

**Comment by diegoferigo** [comment]
No it is not, those are leftovers from the tests I'm currently doing. Fixed.

**Comment by diegoferigo** [comment]
@nunoguedelha I tested in Gazebo, all seems working fine. However, gazebo crashes if the inertial sensors sections are included. I kept them out for the time being. Further tests are needed on this side

**Comment by diegoferigo** [comment]
Friction support has been ported upstream a while ago. Closing this temporary PR.

**Pull request closed without merging**
